from datetime import datetime

import pandas as pd

from base import score_list, standard_list, prompt_list
import os
from tqdm import tqdm

import language_tool_python


# df = pd.read_csv(r'D:\gs\distance_analysis\aes\dataset\ELLIPSE-Corpus\sample_train.csv')

def calculate_grammar_error(text: str) -> int:
    """
    这个是一个检查语法的函数，返回的是这一篇文章有多少语法错误，实际上文章越长，语法错误就有可能越多，但是这并不意味着文章越短评分就应该越高，所以
    可能需要考虑返回一个比例值：（有语法错误的句子）/（总句子）所得到的结果。但是这样实际上也会有些问题，因为如果一个句子出现了多处语法错误，证明
    此文章的水平越低，与只出现一处语法错误的句子不应该一视同仁，经过权衡考虑，打算直接返回章语法错误的数量

    :param text: 输入的文本
    :return: 返回文章语法错误的数量
    """
    tool = language_tool_python.LanguageTool('en-US')  # 对于英语，使用 'en-US'
    try:
        matches = tool.check(text)

        print(matches)
        return len(matches)
    except Exception as e:
        print("Error:", e)
        return 0


base_url = "http://localhost:11434/api"
headers = {
    "Content-Type": "application/json"}


def generate_completion(prompt, model="deepseek-r1", system_prompt=None):
    import requests
    url = f"{base_url}/generate"
    data = {
        "model": model,
        "prompt": prompt,
        "stream": False}

    if system_prompt:
        data["prompt"] = f"{system_prompt}\n{prompt}"
    response = requests.post(url, headers=headers, json=data)
    return response.json().get('response', '')


def generate_text(prompt_list: list, score_list: list, standard_list: list, num_generate: int):
    for j in tqdm(range(num_generate), desc='Generating Texts', unit="generation"):
        for prompt_topic in prompt_list:
            for i, score in enumerate(score_list):
                system_prompt = f"You will act as a student with the English levels {score} (range for 1-5), and write a composition according to the corresponding level standards: {standard_list[i]}. Sometimes you can make some mistakes, such as intentional grammar mistakes, intentional misspelling of words, intentional incoherence of sentences, etc., to make you more like a student."
                prompt_big = "the essay you write before still good enough and not match the requirement, you need to change the article you generated above. You can make more mistakes to suit the target requirements just like a student, such as intentional grammar mistakes, intentional spelling mistakes, intentional sentence incoherence and so on."
                prompt_small = "the essay you write before is a little bad and not match the requirement, you need to change the article you generated above. You can make less mistakes to suit the target requirements but don't remove it all."

                prompt = f"""now you are required to generate a text with the essay's topic: '{prompt_topic}'."""

                completion = generate_completion(prompt=prompt, system_prompt=system_prompt)

                file_name = f"D:/gs/distance_analysis/aes/out/{prompt_topic}/{score}/{str(datetime.isoformat(datetime.now())).split('.')[0].replace(':', '-')}.txt"

                os.makedirs(os.path.dirname(file_name), exist_ok=True)

                with open(file_name, "w", encoding="utf-8") as file:
                    file.write(completion)


def generate_text_first_clean():

    df_dl_ori = pd.read_csv(r"D:\gs\distance_analysis\aes\out\test\aes_lw_dl_with_vcg_2025-3-5.csv")

    df_dl_full = df_dl_ori.sample(frac=1, random_state=42).reset_index(drop=True)

    system_prompt_enhance = """You will act as a english-learner student, now you need to modify the given article(generated by large language model before) to make it look like it was written by an English learner according to the requirements."""

    for index, row in df_dl_full.iterrows():
        v_prompt, g_prompt, c_prompt = '', '', ''
        if int(row['Vocabulary']) < int(row['score']):
            if int(row['score']) - int(row['Vocabulary']) == 2:
                v_prompt = """add more words for the essay or use more varied vocabulary,"""
            elif int(row['score']) - int(row['Vocabulary']) > 2:
                v_prompt = """add lots of words for the essay or use lots of varied vocabulary,"""
        else:
            if int(row['Vocabulary']) - int(row['score']) == 2:
                v_prompt = """reduce some words for the essay or use less varied vocabulary,"""
            elif int(row['Vocabulary']) - int(row['score']) > 2:
                v_prompt = """reduce much words for the essay or use more single words,"""


        if int(row['Grammar']) < int(row['score']):
            if int(row['score']) - int(row['Grammar']) == 2:
                g_prompt = """reduce some grammar errors, but make sure they still exist,"""
            elif int(row['score']) - int(row['Grammar']) > 2:
                g_prompt = """reduce a lot of grammar errors, but make sure they still exist,"""
        else:
            if int(row['Grammar']) - int(row['score']) == 2:
                g_prompt = """add more syntax errors for the essay,"""
            elif int(row['Grammar']) - int(row['score']) > 2:
                g_prompt = """add lots of syntax errors for the essay,"""


        if int(row['Cohesion']) < int(row['score']):
            if int(row['score']) - int(row['Cohesion']) == 2:
                c_prompt = """add more connective word for the essay"""
            elif int(row['score']) - int(row['Cohesion']) > 2:
                c_prompt = """add more connective word for the essay or increase the use of connecting words in your article and add more advanced connecting sentences, such as starting with the present continuous tense of verbs,"""
        else:
            if int(row['Cohesion']) - int(row['score']) == 2:
                c_prompt = """use fewer conjunctions.,"""
            elif int(row['Cohesion']) - int(row['score']) > 2:
                c_prompt = """reduce the use of connective words and advanced connective sentences"""

        file_name = f"D:/gs/distance_analysis/aes/out/first_clean/{row['score']}/{str(datetime.isoformat(datetime.now())).split('.')[0].replace(':', '-')}.txt"

        os.makedirs(os.path.dirname(file_name), exist_ok=True)

        if not (v_prompt + g_prompt + c_prompt):
            with open(file_name, "w", encoding="utf-8") as file:
                file.write(row['text'])
            continue

        prompt_enhance = f"""now you need to modify the specified essay with the essay-prompt: "Distance learning" to match the actual score {row['score']}(range for 1-5). Specifically, you need to {v_prompt}, {g_prompt}, {c_prompt}. In addition, you can use more first-person phrases, such as 'In my opinion', or add practical examples to enrich the essay and make it seem more like it was written by a student. Also, you don't have to start your essay with the essay-prompt 'Distance learning'. the essay is given: {row['text']}"""


        completion = generate_completion(prompt=prompt_enhance, system_prompt=system_prompt_enhance)

        with open(file_name, "w", encoding="utf-8") as file:
            file.write(completion)


if __name__ == '__main__':
    # generate_text(prompt_list, score_list, standard_list, 20000)
    generate_text_first_clean()